
-- Q1. What is the total revenue generated by male vs. female customers?
select 
	gender,
    sum(purchase_amount) as revenue
from mytable
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
with cte as(
select round(avg(purchase_amount),2) as avg_purchase from mytable
)
select 
	m.customer_id,
    m.purchase_amount,
    c.avg_purchase
from mytable m cross join cte c
where discount_applied = 'Yes' and m.purchase_amount >= c.avg_purchase;

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT 
    item_purchased, ROUND(AVG(review_rating), 2) AS Avg_rating
FROM
    mytable
GROUP BY item_purchased
ORDER BY Avg_rating DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT 
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM
    mytable
WHERE
    shipping_type IN ('Standard' , 'Express')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT 
    subscription_status,
    count(*) as total_customer,
    SUM(purchase_amount) AS revenue,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM
    mytable
GROUP BY subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT 
    item_purchased,
    ROUND(100 * SUM(CASE
                WHEN discount_applied = 'yes' THEN 1
                ELSE 0
            END) / COUNT(*),
            2) AS asxd
FROM
    mytable
GROUP BY item_purchased
ORDER BY asxd DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

with cte as(
select 
	customer_id, 
    previous_purchases, 
    case
		when previous_purchases = 1 then 'New'
        when previous_purchases between 2 and 10 then 'Returning'
        else 'Loyal'
	end as customer_seg
from mytable
)
select 
	customer_seg,
    count(*) as no_of_customer
from cte 
group by customer_seg;


-- Q8. What are the top 3 most purchased products within each category?
with cte as (select 
	category,
    item_purchased,
    row_number() over(partition by category order by count(*) desc) as item_rank,
    count(*) as no_of_purchase
from mytable group by category,item_purchased)
SELECT 
    category, item_purchased, item_rank, no_of_purchase
FROM
    cte
WHERE
    item_rank IN (1 , 2, 3);
-- Q9. Are customers who are repeat buyers. (more than 5 previous purchases) also likely to subscribe?

SELECT 
    subscription_status, COUNT(customer_id) AS repeat_buyer
FROM
    mytable
WHERE
    previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group?

SELECT 
    age_group, SUM(purchase_amount) AS revenue
FROM
    mytable
GROUP BY age_group
ORDER BY 2 DESC;

-- Q11. Which location generated the highest total revenue?
SELECT 
    location,
    SUM(purchase_amount) AS total_revenue
FROM 
    mytable
GROUP BY location
ORDER BY total_revenue DESC
LIMIT 5;

-- Q12. What is the average review rating by category?
SELECT 
    category,
    ROUND(AVG(review_rating), 2) AS avg_rating
FROM 
    mytable
GROUP BY category
ORDER BY avg_rating DESC;

-- Q13. Which payment method is most used by customers?
SELECT 
    payment_method,
    COUNT(*) AS usage_count
FROM 
    mytable
GROUP BY payment_method
ORDER BY usage_count DESC;


-- Q14. What is the average purchase frequency (in days) for each customer segment?
WITH seg AS (
    SELECT 
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_seg,
        AVG(purchase_frequency_days) AS avg_freq
    FROM mytable
    GROUP BY customer_id, previous_purchases
)
SELECT 
    customer_seg, 
    ROUND(AVG(avg_freq),2) AS avg_purchase_frequency
FROM seg
GROUP BY customer_seg;

-- Q15. Which season has the highest total revenue?

SELECT 
    season, 
    SUM(purchase_amount) AS total_revenue
FROM 
    mytable
GROUP BY season
ORDER BY total_revenue DESC;


-- Q16. Do discount users give better or worse review ratings?

SELECT 
    discount_applied,
    ROUND(AVG(review_rating), 2) AS avg_rating
FROM 
    mytable
GROUP BY discount_applied;

-- Q17. Which age group makes the highest average purchase amount?

SELECT 
    age_group, 
    ROUND(AVG(purchase_amount), 2) AS avg_purchase
FROM 
    mytable
GROUP BY age_group
ORDER BY avg_purchase DESC;

-- Q18. Which color and size combination sells the most?
SELECT 
    color, 
    size, 
    COUNT(*) AS total_sales
FROM 
    mytable
GROUP BY color, size
ORDER BY total_sales DESC
LIMIT 10;

-- Q19. Which shipping type gives higher review ratings?
SELECT 
    shipping_type, 
    ROUND(AVG(review_rating), 2) AS avg_rating
FROM 
    mytable
GROUP BY shipping_type
ORDER BY avg_rating DESC;

-- Q20. What is the average purchase amount by gender and category?
SELECT 
    gender,
    category,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase
FROM 
    mytable
GROUP BY gender, category
ORDER BY avg_purchase DESC;
